// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGroupForCustomer(arg1, arg2) {
  return window['go']['main']['App']['CreateGroupForCustomer'](arg1, arg2);
}

export function GetContacts(arg1) {
  return window['go']['main']['App']['GetContacts'](arg1);
}

export function GetFollowUserList() {
  return window['go']['main']['App']['GetFollowUserList']();
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMembers() {
  return window['go']['main']['App']['GetMembers']();
}

export function GetRootMode() {
  return window['go']['main']['App']['GetRootMode']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTestAccounts() {
  return window['go']['main']['App']['GetTestAccounts']();
}

export function IsAgentRunning() {
  return window['go']['main']['App']['IsAgentRunning']();
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function SaveTestAccounts(arg1) {
  return window['go']['main']['App']['SaveTestAccounts'](arg1);
}

export function SetRootMode(arg1) {
  return window['go']['main']['App']['SetRootMode'](arg1);
}

export function StartAutoAgent() {
  return window['go']['main']['App']['StartAutoAgent']();
}

export function StartLoadContacts(arg1) {
  return window['go']['main']['App']['StartLoadContacts'](arg1);
}

export function StopAutoAgent() {
  return window['go']['main']['App']['StopAutoAgent']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
