// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateGroupForCustomer(arg1:string,arg2:string):Promise<main.GroupResult>;

export function GetContacts(arg1:string):Promise<Array<main.Contact>>;

export function GetFollowUserList():Promise<Array<string>>;

export function GetGroups():Promise<Array<main.GroupChat>>;

export function GetLogs():Promise<Array<string>>;

export function GetMembers():Promise<Array<main.Member>>;

export function GetSettings():Promise<main.AppState>;

export function GetTestAccounts():Promise<Array<string>>;

export function IsAgentRunning():Promise<boolean>;

export function SaveSettings(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function SaveTestAccounts(arg1:Array<string>):Promise<void>;

export function StartAutoAgent():Promise<string>;

export function StartLoadContacts(arg1:string):Promise<void>;

export function StopAutoAgent():Promise<string>;

export function TestConnection():Promise<string>;
